In [1]:
import numpy as np

In [2]:
python_list = [1,2,3,5,-5]

In [3]:
python_list

[1, 2, 3, 5, -5]

In [5]:
numpy_array = np.array(python_list)

In [7]:
len(numpy_array.shape)

1

In [8]:
python_list_list = [[1,2],[3,4]]

In [9]:
python_list_list

[[1, 2], [3, 4]]

In [11]:
numpy_arr2 = np.array(python_list_list)

In [12]:
len(numpy_arr2.shape)

2

In [13]:
numpy_arr2.shape

(2, 2)

In [14]:
python_list_list = [[1,2,5],[3,4,6]]

In [15]:
np.array(python_list_list).shape

(2, 3)

In [16]:
list(range(5))

[0, 1, 2, 3, 4]

In [17]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [18]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [19]:
np.zeros((2,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [20]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [23]:
np.random.randint(5)

2

In [24]:
np.random.randint(5,size=[2,2])

array([[0, 1],
       [4, 1]])